default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rc_pro_quotes_development
  username: rc_pro_quotes
  password: password

test:
  <<: *default
  database: rc_pro_quotes_test

production:
  <<: *default
  database: rc_pro_quotes_production
  username: rc_pro_quotes
  password: <%= ENV["RC_PRO_QUOTES_DATABASE_PASSWORD"] %>

